namespace: jerney

frontend:
  replicaCount: 1
  image:
    repository: jerney-frontend
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 1
  image:
    repository: jerney-backend
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  database: jerney_db
  username: jerney_user
  password: change_me
  storage: 1Gi

ingress:
  enabled: true
  className: traefik
  host: jerney.local
